# Site settings

# NB! Set your site's url, otherwise nothing will work
url: "https://iamcot.github.io/"

# Google tracking id
# google-tracking-id: "UA-XXXXXXXX-X"

#############
# HTML Head #
#############

lang: "en"
author: "CoT"
title: "{ IamCoT }"
description: "CoT's blog, a code lover, travel lover and an ironman"
keywords: "cot, blog, code, travel, ironman"
favicon: "/img/favicon.ico"
################
# Header layout#
################
black-favicon: "/img/black-lab-glass.ico"
background-img: "intro-bg.jpg"

##############################
# Dynamic Text on the Header #
##############################

quote: "What is to be, will be, and all will be well."
me-img: "/img/cotcanon.jpg"

# To use github profile pic uncomment the following line and replace 'user_name'
# with your github user name.

# me-img: "https://github.com/user_name.png?size=500"

# To use gravatar profile pic uncomment the following line and replace 'email_hash'
# with your gravatar profile email hash.
# You can create the email hash by using an online tool like 'http://www.md5hashgenerator.com/'
# just enter your email and it will generate the hash.

# me-img: "https://www.gravatar.com/avatar/email_hash?s=500"

#######
# Blog #
########

post-preview-words: 96
paginate: 5
email-share: True
fb-share: True
twitter-share: True
linkedin-share: True
reddit-share: True
tumblr-share: True
pinterest-share: True
pocket-share: True
vkontakte-share: True

disqus-shortname: "iamcot-blog"

############
# Timeline #
############

events:
  - image: "/img/timeline/lazada.png"
    date: "Oct 2014 - Jan 2024"
    description: "From Developer to Senior Manager at LAZADA"
  - image: "/img/timeline/vast.png"
    date: "Jan 2012 - Oct 2013"
    description: "a Leader also a Researcher at VAST"
  - image: "/img/timeline/vgs.png"
    date: "Jan 2010 - Jan 2012"
    description: "The first IT job as a developer at VGS"
  - image: "/img/timeline/ptit.png"
    date: "Sep 2005 - Sep 2010"
    description: "A naughty IT student at PTIT"

# First image of the Timeline
timeline-img: "/img/timeline/default.jpeg"

###########
# Contact #
###########

email: "iamcot@gmail.com"
# Set a url pointing to your publish PGP Public Key here, and it will appear in the Contact section
pgp: False

################
# Author Blurb #
################

# The author blurb goes underneath blog posts.
# This works best when your author blurb image has a transparent background, or matches your site background color.

# if the author_blurb is not set, then this feature is skipped
author_blurb:
  "For CoT, the World is his playground. When he's not crafting elegant code, he's exploring new horizons, whether it's on foot, by bike, or in the water."
author_blurb_image: "/img/cotcanon.jpg"

##################
# Social Buttons #
##################

social:
  - icon: "github"
    url: "https://github.com/iamcot"
  - icon: "linkedin-in"
    url: "https://www.linkedin.com/in/iamcot"

# NB! Tread carefully if you want to change the variables below this point!

# Sections shown in the index page
pages_list:
  About: "about"
  Blog: "latest-post"
  Timeline: "timeline"
  Contact: "contact"
# Exclusion list from the generated _site
exclude:
  - LICENSE
  - README.md
  - CONTRIBUTING
  - CONTRIBUTORS
  - scripts
  - Dockerfile
  - docker-compose.yml
# Pagination path
paginate_path: "blog/page:num/"
# Enable minification SASS
sass:
  style: compressed
plugins:
  - jekyll-paginate
  - jekyll-spaceship
